select * from customer ;

#Q1. What is the total revenue generated by male vs. female customers?
SELECT distinct(gender), SUM(purchase_amount) AS revenue from customer
group by gender;
 
#Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id , purchase_amount from customer
WHERE discount_applied="Yes" AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

#Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased AS products , Round(AVG(review_rating),2) AS "Highest avg rating" from customer
group by products
ORDER by AVG(review_rating) DESC
limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT Round(AVG(purchase_amount),2) AS "AVG purchase amt" , shipping_type from customer
WHERE shipping_type in ("Standard" , "Express")
Group by shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status , Round(AVG(purchase_amount),2) AS average_spend , Round(SUM(purchase_amount),2) AS total_revenue
from customer
group by subscription_status ;

#Q6. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select Count(customer_id) AS "repeat buyers" , subscription_status from customer 
where previous_purchases > 5 
group by subscription_status;

#Q7. What is the revenue contribution of each age group? 
select sum(purchase_amount) AS "revenue contribution", age_group from customer 
group by age_group;